ingress:
  enabled: true
  ingressClassName: nginx
  hostname: myapp.local
  annotations: {}
  tls: []
  pathType: Prefix
  paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: frontend-nginx
          port:
            number: 80

service:
  type: ClusterIP
  port: 80

serverBlock: |-
  server {
    listen 80;
    root /app;
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }

    location /minio/ {
      proxy_pass http://minio.minio.svc.cluster.local:9000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     }

  }

extraVolumes:
  - name: html-content
    configMap:
      name: frontend-html

extraVolumeMounts:
  - name: html-content
    mountPath: /app
