## @param defaultBuckets Comma separated list of buckets to create on MinIO startup.
defaultBuckets: "my-test-bucket"

auth:
  ## @param auth.rootUser MinIO root username. Ignored if `auth.existingSecret` is set.
  rootUser: admin

  ## @param auth.rootPassword MinIO root password. Ignored if `auth.existingSecret` is set.
  rootPassword: "PolskieRadio"

  ## @param auth.existingSecret Use existing Kubernetes Secret for credentials details.
  ## If set, `auth.rootUser` and `auth.rootPassword` are ignored and values are loaded from this secret.
  existingSecret: ""

ingress:
  ## @param ingress.enabled Enable or disable ingress for MinIO service.
  enabled: true

  ## @param ingress.ingressClassName Name of the ingress class to use.
  ingressClassName: nginx

  ## @param ingress.hostname Hostname to use for ingress rules.
  hostname: myapp.local

  ## @param ingress.path Path used for ingress routing.
  path: /minio(/|$)(.*)

  ## @param ingress.pathType Path type for ingress routing. Must be ImplementationSpecific for rewrite rules.
  pathType: ImplementationSpecific

  ## @param ingress.annotations Additional annotations for ingress resource.
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2

  ## @param ingress.servicePort Target port of the MinIO service to route traffic to.
  servicePort: minio
